# Generated by Django 2.0 on 2020-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('area', models.CharField(max_length=20, unique=True)),
                ('topology', models.CharField(max_length=20, unique=True)),
                ('priority', models.CharField(max_length=40, unique=True)),
                ('test_type', models.CharField(max_length=40, unique=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
