# Generated by Django 2.0 on 2020-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0002_auto_20200426_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=30)),
                ('case', models.TextField()),
                ('testbed', models.TextField()),
                ('profile', models.TextField()),
                ('parameter', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cases',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cases',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='priority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cases',
            name='test_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cases',
            name='topology',
            field=models.CharField(max_length=30),
        ),
    ]
