# Generated by Django 2.0 on 2020-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0003_auto_20200427_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='topology',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='cases',
            name='parameter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='testbed',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='parameter',
            field=models.TextField(null=True),
        ),
    ]
