# Generated by Django 2.0 on 2020-04-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0004_auto_20200429_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='profile',
            new_name='topology',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='testbed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
