# Generated by Django 2.0 on 2020-05-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0006_parameter_topology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parameter',
        ),
    ]
