# Generated by Django 2.0 on 2020-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0007_remove_project_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parameter',
            field=models.TextField(null=True),
        ),
    ]
