# Generated by Django 2.0 on 2020-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0008_project_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topology',
            name='value',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
