# Generated by Django 2.0 on 2020-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0009_auto_20200502_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='duration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='equipment',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='identifier',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='procedure',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='timeout',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='priority',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='test_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='topology',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
