# Generated by Django 2.0 on 2020-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0010_auto_20200505_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='equipment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='procedure',
            field=models.TextField(null=True),
        ),
    ]
