# Generated by Django 2.0 on 2020-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0011_auto_20200505_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='idle', max_length=30),
        ),
    ]
