# Generated by Django 2.0 on 2020-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0013_auto_20200510_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parameter',
        ),
        migrations.AddField(
            model_name='project',
            name='modifyTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
