# Generated by Django 2.0 on 2020-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0014_auto_20200510_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('execution', models.DateTimeField()),
                ('duration', models.CharField(max_length=30)),
                ('passed', models.CharField(max_length=50, unique=True)),
                ('total', models.CharField(max_length=50, unique=True)),
                ('logPath', models.TextField()),
            ],
        ),
    ]
