# Generated by Django 2.0 on 2020-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0015_recenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lastRun',
            field=models.DateTimeField(null=True),
        ),
    ]
