# Generated by Django 2.0 on 2020-05-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0016_project_lastrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='passed',
            field=models.IntegerField(null=True),
        ),
    ]
