# Generated by Django 2.0 on 2020-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0017_project_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recenttest',
            name='passed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recenttest',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
