# Generated by Django 2.0 on 2020-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0019_project_console'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='passed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
