# Generated by Django 2.0 on 2020-05-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0020_auto_20200517_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttest',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
