# Generated by Django 2.0 on 2020-05-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpackdb', '0021_auto_20200518_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
